name: Release alpha

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout
#         with:
#           #        ref: develop
#           token: ${{ secrets.MY_TOKEN }}
#           submodules: true

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Pass Environment variables
        run: echo Build number is $BUILD_NUMBER

      - name: Unit Test
        run: ./gradlew testAlphaReleaseUnitTest
#        continue-on-error: true # Allow steps to continue even with test failures
        continue-on-error: false

      #    - name: Report
      #       uses: asadmansr/android-test-report-action@master

      - name: Build
        run: ./gradlew :app:assembleAlphaRelease

      - name: Archive apk
        uses: actions/upload-artifact@v1
        with:
          name: owl-random
          path: app/build/outputs/apk/alphaRelease/owl-random.apk
